server:
  port: 8762

eureka:
  instance:
    hostname: eureka-server

  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: https://${eureka.instance.hostname}:${server.port}/eureka/
